### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by bozoweed** [KWMSources/pedSyncer#3]
[21:14:01] Loading resource pedSyncer2
[INFO] GameEntityResource InitEntitySync startet
Started
[21:14:01] Search File C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\server\newNavigationMeshes.msgpack
[21:14:02] Failed loading dump: MessagePack.MessagePackSerializationException: Failed to deserialize System.Collections.Generic.List`1[[NavMesh_Graph.NavigationMeshPolyFootpath, pedSyncer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] value.
 ---> System.TypeInitializationException: The type initializer for 'FormatterCache`1' threw an exception.
 ---> System.NotSupportedException: A non-collectible assembly may not reference a collectible assembly.
   at System.Reflection.Emit.ModuleBuilder.GetTypeRef(QCallModule module, String strFullName, QCallModule refedModule, String strRefedModuleFileName, Int32 tkResolution)
   at System.Reflection.Emit.ModuleBuilder.GetTypeRefNested(Type type, Module refedModule, String strRefedModuleFileName)
   at System.Reflection.Emit.ModuleBuilder.GetTypeTokenWorkerNoLock(Type type, Boolean getGenericDefinition)
   at System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(Type type, Boolean getGenericDefinition)
   at System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker(Type clsArgument, Boolean lastWasGenericInst)
   at System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker(Type clsArgument, Boolean lastWasGenericInst)
   at System.Reflection.Emit.SignatureHelper.GetTypeSigToken(Module module, Type type)
   at System.Reflection.Emit.ModuleBuilder.GetTypeTokenWorkerNoLock(Type type, Boolean getGenericDefinition)
   at System.Reflection.Emit.ModuleBuilder.GetTypeTokenInternal(Type type, Boolean getGenericDefinition)
   at System.Reflection.Emit.TypeBuilder..ctor(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
   at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent, Type[] interfaces)
   at MessagePack.Internal.DynamicAssembly.DefineType(String name, TypeAttributes attr, Type parent, Type[] interfaces)
   at MessagePack.Internal.DynamicObjectTypeBuilder.BuildType(DynamicAssembly assembly, Type type, Boolean forceStringKey, Boolean contractless)
   at MessagePack.Resolvers.DynamicObjectResolver.FormatterCache`1..cctor()
   --- End of inner exception stack trace ---
   at MessagePack.Resolvers.DynamicObjectResolver.GetFormatter[T]()
   at MessagePack.Resolvers.StandardResolver.FormatterCache`1..cctor()
--- End of stack trace from previous location where exception was thrown ---
   at MessagePack.Formatters.ListFormatter`1.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](ReadOnlyMemory`1 buffer, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at navMesh_Graph_WebAPI.NavigationMeshControl.LoadDataFromDumpFile[TDumpType](String dumpFileName) in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\NavigationMeshControl.cs:line 133
[21:14:02] < ==== UNHANDLED EXCEPTION ==== >
 Received an unhandled exception from : System.NullReferenceException: Object reference not set to an instance of an object.
   at navMesh_Graph_WebAPI.NavigationMeshControl..ctor() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\NavigationMeshControl.cs:line 25
   at navMesh_Graph_WebAPI.NavigationMeshControl.getInstance() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\NavigationMeshControl.cs:line 123
   at PedSyncer.PedSyncer.OnStart() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\PedSyncer.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
 < ==== UNHANDLED EXCEPTION ==== >
 Received an unhandled exception from : System.NullReferenceException: Object reference not set to an instance of an object.
   at navMesh_Graph_WebAPI.NavigationMeshControl..ctor() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\NavigationMeshControl.cs:line 25
   at navMesh_Graph_WebAPI.NavigationMeshControl.getInstance() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\NavigationMeshControl.cs:line 123
   at PedSyncer.PedSyncer.OnStart() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\PedSyncer.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
[21:14:02] Loaded resource pedSyncer2
Unhandled exception. [21:14:02] Loading resource 420core
System.NullReferenceException: Object reference not set to an instance of an object.
   at navMesh_Graph_WebAPI.NavigationMeshControl..ctor() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\NavigationMeshControl.cs:line 25
   at navMesh_Graph_WebAPI.NavigationMeshControl.getInstance() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\NavigationMeshControl.cs:line 123
   at PedSyncer.PedSyncer.OnStart() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\PedSyncer.cs:line 51
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by KWMSources** [comment]
Please follow this workaround: https://github.com/DurtyFree/gta-v-data-dumps/blob/master/navigationmesh.md

**Comment by bozoweed** [comment]
i did it but nothing change

**Comment by bozoweed** [comment]
now it's sayed that
[00:15:55] Loading resource pedSyncer2
WARNING: AltV.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null is not collectible and will prevent you from dynamically starting and stopping resources.
WARNING: AltV.Net.EntitySync, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null is not collectible and will prevent you from dynamically starting and stopping resources.
WARNING: AltV.Net.EntitySync.ServerEvent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null is not collectible and will prevent you from dynamically starting and stopping resources.
[INFO] GameEntityResource InitEntitySync startet
Started
WARNING: MessagePack, Version=2.1.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be is not collectible and will prevent you from dynamically starting and stopping resources.
[00:15:56] Search File C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\server\newNavigationMeshes.msgpack
WARNING: MessagePack.Annotations, Version=2.1.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be is not collectible and will prevent you from dynamically starting and stopping resources.
[00:15:56] Successfully loaded dump file resources\pedSyncer2\server\newNavigationMeshes.msgpack.
[00:15:56] NavMeshFootPath Count: 98911
[00:15:56] Search File C:\Users\Administrateur\Desktop\Mystery Altv\resources/pedSyncer2/server/StreetCrossings.json
[00:15:56] Failed loading dump: System.NotSupportedException: Deserialization of reference types without parameterless constructor is not supported. Type 'NavMesh_Graph.WorldVector3'
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeCreateObjectDelegateIsNull(Type invalidType)
   at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at pedSyncer.control.StreetCrossingControl.LoadDataFromJsonFile[TDumpType](String dumpFileName) in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\StreetCrossingControl.cs:line 53
[00:15:56][00:15:56][00:15:56] < ==== UNHANDLED EXCEPTION ==== >
 Received an unhandled exception from : System.NullReferenceException: Object reference not set to an instance of an object.
   at pedSyncer.control.StreetCrossingControl..ctor() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\StreetCrossingControl.cs:line 22
   at pedSyncer.control.StreetCrossingControl.getInstance() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\StreetCrossingControl.cs:line 32
   at PedSyncer.PedSyncer.OnStart() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\PedSyncer.cs:line 54
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
 Loaded resource pedSyncer2
Unhandled exception. [00:15:56] Loading resource 420core
System.NullReferenceException: Object reference not set to an instance of an object.
   at pedSyncer.control.StreetCrossingControl..ctor() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\StreetCrossingControl.cs:line 22
   at pedSyncer.control.StreetCrossingControl.getInstance() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\control\StreetCrossingControl.cs:line 32
   at PedSyncer.PedSyncer.OnStart() in C:\Users\Administrateur\Desktop\Mystery Altv\resources\pedSyncer2\pedSyncer\PedSyncer.cs:line 54
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
WARNING: AltV.Net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null is not collectible and will prevent you from dynamically starting and stopping resources.

**Comment by KWMSources** [comment]
Did you changed the StreetCrossing-path by yourself? I guess you compiled it yourself...

The exception-stack let me guess that you dont use the Newtonsoft-Json-Deserializer, but the c# native json deserializer. Maybe loading the newton json deserializer from nuget will solve the problem.
