### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by FDiskas** [KWMSources/pedSyncer#7]
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
      at Ped
      at PedSyncer.Control.NavigationMesh.getInstance() in F:\Projekte\pedSyncer\src\control\NavigationMesh.cs:line 167
      at PedSyncer.PedSyncer.OnStart() in F:\Projekte\pedSyncer\src\PedSyncer.cs:line 56
```

**Comment by TheLexoPlexx** [comment]
Full log of the same Error: [server.log](https://gist.githubusercontent.com/TheLexoPlexx/f981b8c369e18ce996c8f27d7c4f1bdb/raw/756e034a4d0b3315c1cb7ea90fc24ec34d6b55ce/server.log)

**Comment by eMKey1988** [comment]
For me, this error occured because i renamed my pedSyncer - resourcefolder to something else. It has to be "pedSyncer".
The NavigationMesh constructor calls a function searching for "resources/pedSyncer/server/newNavigationMeshes.msgpack" and if this file couldn't be found, you get this error.
