### ISSUE TITLE
Unhandled exception when loading program

### ISSUE THREAD

**Issue by alextwothousand** [KWMSources/pedSyncer#8]
```
[16:03:29] Search File P:\Programming\AltV\PilotsLifeV\resources/pedSyncer/server/newNavigationMeshes.msgpack
[16:03:29] Could not find dump file at P:\Programming\AltV\PilotsLifeV\resources/pedSyncer/server/newNavigationMeshes.msgpack
[16:03:29] < ==== UNHANDLED EXCEPTION ==== >
 Received an unhandled exception from : System.NullReferenceException: Object reference not set to an instance of an object.
   at PedSyncer.Control.NavigationMesh..ctor() in F:\Projekte\pedSyncer\src\control\NavigationMesh.cs:line 27
   at PedSyncer.Control.NavigationMesh.getInstance() in F:\Projekte\pedSyncer\src\control\NavigationMesh.cs:line 167
   at PedSyncer.PedSyncer.OnStart() in F:\Projekte\pedSyncer\src\PedSyncer.cs:line 56
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at PedSyncer.Control.NavigationMesh..ctor() in F:\Projekte\pedSyncer\src\control\NavigationMesh.cs:line 27
   at PedSyncer.Control.NavigationMesh.getInstance() in F:\Projekte\pedSyncer\src\control\NavigationMesh.cs:line 167
   at PedSyncer.PedSyncer.OnStart() in F:\Projekte\pedSyncer\src\PedSyncer.cs:line 56
```

**Comment by eMKey1988** [comment]
For me, this error occured because i renamed my pedSyncer - resourcefolder to something else. It has to be "pedSyncer".
The NavigationMesh constructor calls a function searching for "resources/pedSyncer/server/newNavigationMeshes.msgpack" and if this file couldn't be found, you get this error.
